apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-argocd
    annotations:
        argocd.argoproj.io/sync-wave: "15"
spec:
    acme:
        # The ACME server URL
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: abhinav.gyawali@feldera.com
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: letsencrypt-argocd
        # Enable the DNS-01 challenge provider
        solvers:
            - dns01:
                  route53:
                      region: us-west-1
                      role: arn:aws:iam::586549104403:role/AwsFelderaCloudDnsAccess
