apiVersion: v1
kind: Secret
metadata:
    name: sandbox-staging-secret
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: "sandbox-staging"
    server: "https://57E0C76A3E55345956B58C1D1C882DCA.sk1.us-west-1.eks.amazonaws.com"
    config: |
        {
          "awsAuthConfig": {
            "clusterName": "staging-cluster",
            "roleARN": "arn:aws:iam::905418091519:role/argocd-staging-access"
          },
          "tlsClientConfig": {
            "insecure": false,
            "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQkZxYVgyVjJpY293RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UUXhPVFV6TlROYUZ3MHpOVEV4TVRJeE9UVTROVE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQzY29CeUhGTkEvdFRtTFZBWVhBN1JpcXVWdFNGSEhUV1RqS25WL0xiZ2FWU2VpTmtrMzFBa0x6bFAKbXhYZzhvdVVIQ01vc0k4eGhsSHV4SDE0c0JKR3ZqWmF0czgwVHVlZmVhVDhXanE0RnFvZlBHbmF2cHZLelByYgp0UHlCcmd6aWlkU1dSbnlsTkl0WUpMTUZMcTliRUZWTXZQbVhnaElxWUFXUjdZMTFKeFhPY0hGSTlLU1M0a21CCnViVzF6dDZZbTRwZ2pNbzl5OFZzV0FYVUM4MU5NekE4ekRuSWdCRlN0WG5kNUJEZTBMWVJaVzFVcUVuV1pXQjYKVzIxd2VFVFVHTUFyY2xZK3lVNmtFMUtSdUpBb1ZXVDJFRjlhWUtsYzBWWS80Tk1zQlFHWExWYkJodU9lcjRqbApMODV6L3JRYkw0ZDljZXFQNldqb05NTmM2RHh0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTT0s0b2h2Q3Y1VU5WVU5QQS9hc2RkcUJ1R2NUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQW0xczBFalJNNgprQytCTlZXekhWb08zczJiTmVLaWpwditBcDVBRnNBR01zK2FVZVFBNU5DZWsxRUF3UVB0a0Q3UzhDaWhUbkJ1CkZaaHIxbXNidzdmVlRhdm9KcWViajNkQXB3Wkp6OE5tVnU2ekwzcE1CMnVoOGMxZE4rL0pCZEFTemIyNjVDd1cKVVR4YzlITWlCQ09zNnorK0ZwdlNmWU9jM3pJUlFaMFhWMjRZYWYvbWlIekRWdkVIYVVvbXZmdkVyNGVLbytwMgpXeVhxdnJYamhaL2ZPNnE4TStZbS9paFBmZ05sd3YrTy9GeW5saWVhWVhiKzRBTXhBam50ZHB0bnNOUWVWTEhuCmNQWVgzVHlWUmtoTXk4VFBYOTVUdjBobU1EMHBid1JWY2M2SkphVUdqMjBkSWlkeGRJaTVnODNnMGFqK1lIaTEKeHN6QWpvYjhSMXlKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          }
        }
