apiVersion: v1
kind: Secret
metadata:
    name: sandbox-staging-secret
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: "sandbox-staging"
    server: "https://898B99AF20F679BBAACC105B596FD0F1.yl4.us-west-1.eks.amazonaws.com"
    config: |
        {
          "awsAuthConfig": {
            "clusterName": "staging-cluster",
            "roleARN": "arn:aws:iam::905418091519:role/argocd-staging-access"
          },
          "tlsClientConfig": {
            "insecure": false,
            "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRk5TZDZDTXBIV2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UTXhPVE00TXpaYUZ3MHpOVEV4TVRFeE9UUXpNelphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNZR0JDSUJ5eThpRHRWQklkdmM5QUdGTGlrL0FVQVFUUkpTU3NIYjJUNURFUi9ITEw1aTJ5eDhJZnYKU0lwa1cwZFJXQXBYSEpJbnUyT2xpUnJxYUpMM0V1YXozN0VkeDliS2MyM1RmcElzK04yZDVHaFhHMWg0dTE5bgo5cnFqMHZBd01HcjBwUUROMnZuKzZnSlBDU3MvbjFmb1BiK0pEeVM4NVdxeVI0ZnZSTjh0UENJWmphRjg5eUc5ClJMK3dkUmtkbkFRMjZGd2ZhY0l1c0pmSWN0b2hOYzZ6QkhNWEdVbCtqYVBYbWNUR3A0UUErelpYNGFPQWhOaHYKV3R6dkRhbzBBL3RqWUNBbzBZZjlrN01yTTJHMTJCTDdKSU5DMlRWVThFbjZTa3ZablBnNG5yUXM5cy9ZRHQxcApHMEE0STlrYithemlTUmxTTU82T1pveVBXWFp4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRTk9WUUY3R0dGdWhTMnQzb0dpTmxhbDd6eTV6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZyeG43ejl3QgpqRzVXejlieXROcTVGK01KNE1VMlJETVBwQ2R0ZFJzb0ZTQXlyY0lXU0VCSHJ6eWR0NzQ4aGxxR3A4Wk81SElDCm9OMk1XOXVRVXltMklmcmtEbEhoWGdUUFQ3Y1lKalBIanNDdVpxYUc0ejBRWHFNTXU1citISS9ZaldqQVlIaGMKMndsOSs2QmpQMk0vVWk0UlRRRFBqYmR3aSs1eWVRWXJPRFI2TFJZVVZ3aTNRWC9MaGVSMW5DMjFkdysrOHgreApmR3NQQ1NZODc3T3I4TnYzVGFiTTdJL1NTdUZnV3d6dThsUFY5UTRxa1ptSEtoUXpyYXNGRE5icXBoTTBEWHJWCmc2QjRqUjFJVFA0QmRuVFBwTFhwcnkvSjErbkFyME4rS290a2pEWFpUTU0yTC9ZcE1nUFNLL0hqSHNLYXNjYzkKTXh0Z1NzS3h1L3hMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          }
        }
