apiVersion: v1
kind: Secret
metadata:
    name: sandbox-staging
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: "sandbox-staging"
    server: "https://A80857069F795C3DEBA8317492774E46.sk1.us-west-1.eks.amazonaws.com"
    config: |
        {
          "awsAuthConfig": {
            "clusterName": "staging-cluster"
          },
          "tlsClientConfig": {
            "insecure": false,
            "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWHJ0Rjc1eDBoMmd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UWXhNelU1TWpkYUZ3MHpOVEV4TVRReE5EQTBNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURvYmNOMG95ei9kT0NiTFh2cUpOdjJoNDVGZXNweEdueDlnU1NZMGphZ1I5cllrVnVnTWovN3VZZWgKeUk5cERFYmUwckwzNW5BRFAveFl0d0xucEd6aFZzUmxWdzkzMXBhZVM2NFM2dXBzNUNyUklIV1J5eCtDUzBvTQpmeHhpVnhOSnFrUXdMdGQ4TW1QVWZWN3IyL3ZqcnhPa3htTnJNN2I3ZGp0cnNUTE4zUHJWY2lEWXpndThqR05sCm5EUkovS2dPWHVPd2RYcmx5aTd1bmVvazZSZjg5eHpSTU9mK1lUSkZYcW9PcGZhaDBPUVk3TmRGODFXNTFUVEYKOUxkOTNwNWFFdVNRWEx5ZjZrdnFjTnJpVDZXZndCaEt0ajAzcTJOVUJjcTg2c0J3YXdWb1JkZDFYdXBGeWNyegpqN3NDQzM5ZCtKcC9Pa0RtVDluV0pHQzU3bWRwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRQVZUajc2R01FdW00RTFQdWdXQXZOdjNRblNqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTJzaFdiQkxwNwo3bjBPNjFVWmhIYWoxMHR6ZkxmV3QvTUx2bk0vZ3dwZElvdjRvVHFidVN3Mng3SVlCZ1VWbzdzdDkxUFZKZ2IxCjhGUUdKdXBHdjV2NEUyZWI4NGNhYnBTQTdFMmhIMXR2YU15U2xnY2xYLzJad1pydUlQWFlxaGwyckxIOXlvdVgKYjBUdzFFcSs2VkVzTVJ2T3k5M1hOUWo2dFJsSzk5NHp5MHgvSHdMY05tbllmRzNzZ0ZmOWxEaE8vNHhTNmRRcApDV1k3OEg0TWhXUEI0OHNlUjlhSUkxREZhRCtrL1l3WlVic1NWQTZBR0hyWm1BU2hUYVVTSk9FZkZvNmh6TitECnpZaXVrOVVXQ1ZYQ0dFaXB1cVpiaXBhUFh0bTRmWEJJNDQ5OVRWWDdyakR4T3gwcGhLc3VITHcxZnVRR2NjbTgKWEtwcXlERXlVQWxQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          }
        }
