# apps/external-secrets/aws-cluster-secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-secret-store
spec:
    provider:
        aws:
            service: SecretsManager
            region: us-east-1 # Replace with your AWS region
            auth:
                jwt:
                    serviceAccountRef:
                        name: external-secrets-operator-external-secrets # Verify this SA name after ESO install
                        namespace: external-secrets
