# apps/external-secrets/aws-cluster-secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-secret-store
    annotations:
        argocd.argoproj.io/sync-wave: "0" # Deploy after ESO
spec:
    provider:
        aws:
            service: SecretsManager
            region: us-west-1
            auth:
                jwt:
                    serviceAccountRef:
                        name: external-secrets-operator-external-secrets # Verify this SA name after ESO install
                        namespace: external-secrets
